---

version: '3'

tasks:
  lint:init:
    preconditions:
      - node --version
    cmds:
      - npm install

  lint:
    deps:
      - lint:init
    cmds:
      - npm run lint

  # TODO: Add some tests via playwright?
  test:
    cmds:
      - sleep 0
