---

kind: pipeline
type: docker
name: docs

steps:
  - name: tests
    image: agrrh/cigp
    commands:
      - task docs:tests

---

kind: pipeline
type: docker
name: backend

steps:
  - name: tests
    image: agrrh/cigp
    commands:
      - task backend:tests

---

kind: pipeline
type: docker
name: frontend

steps:
  - name: tests
    image: agrrh/cigp
    commands:
      - task frontend:tests
