---

kind: pipeline
type: docker
name: lint

steps:
  - name: lint
    image: agrrh/cider  # TODO Freeze version
    commands:
      - go-task lint

---

kind: pipeline
type: docker
name: test

steps:
  - name: test
    image: agrrh/cider  # TODO Freeze version
    commands:
      - go-task test
