---

kind: pipeline
type: docker
name: lint

trigger:
  event:
    - pull_request

steps:
  - name: lint
    image: agrrh/cider:0.2.0
    commands:
      - go-task lint

---

kind: pipeline
type: docker
name: build-pr

trigger:
  event:
    - pull_request

steps:
  - name: backend
    image: plugins/docker
    settings:
      purge: false
      context: ./backend
      dockerfile: ./backend/Dockerfile
      username: agrrh
      password:
        from_secret: docker_password
      repo: agrrh/quotes-backend
      # auto_tag: true
      tags:
        - latest
        - ${DRONE_COMMIT_SHA}

  - name: frontend
    image: plugins/docker
    settings:
      purge: false
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
      username: agrrh
      password:
        from_secret: docker_password
      repo: agrrh/quotes-frontend
      # auto_tag: true
      tags:
        - latest
        - ${DRONE_COMMIT_SHA}

---

kind: pipeline
type: docker
name: build-push-or-tag

trigger:
  event:
    - cron
    - push
    - tag

steps:
  - name: backend
    image: plugins/docker
    settings:
      purge: false
      context: ./backend
      dockerfile: ./backend/Dockerfile
      username: agrrh
      password:
        from_secret: docker_password
      repo: agrrh/quotes-backend
      auto_tag: true

  - name: frontend
    image: plugins/docker
    settings:
      purge: false
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
      username: agrrh
      password:
        from_secret: docker_password
      repo: agrrh/quotes-frontend
      auto_tag: true

---

kind: pipeline
type: docker
name: test

trigger:
  event:
    - pull_request

depends_on:
  - build-pr

steps:
  - name: application
    detach: true
    image: agrrh/quotes-backend:${DRONE_COMMIT_SHA}
    environment:
      APP_DB_URL: "postgresql://quotes:password@postgres/quotes"
    commands:
      - sleep 15
      - uvicorn main:app --host 0.0.0.0 --port 3000

  - name: test
    image: agrrh/cider:0.2.0
    environment:
      APP_URL: "http://application:3000"
    commands:
      - sleep 30
      - go-task test

services:
  - name: postgres
    image: postgres:14.5
    environment:
      POSTGRES_USER: quotes
      POSTGRES_PASSWORD: password
      POSTGRES_DB: quotes
