---

kind: pipeline
type: docker
name: backend-pr

trigger:
  event:
    - pull_request

steps:
  - name: lint
    image: ghcr.io/mgechev/revive:1.2.4
    commands:
      - cd ./backend
      - revive -set_exit_status ./

  - name: build
    depends_on:
      - lint-backend
    image: plugins/docker
    settings:
      purge: false
      context: ./backend
      dockerfile: ./backend/Dockerfile
      username: agrrh
      password:
        from_secret: docker_password
      repo: agrrh/quotes-backend
      tags:
        - ${DRONE_COMMIT_BRANCH}
        - ${DRONE_COMMIT_SHA}

---

kind: pipeline
type: docker
name: frontend-pr

trigger:
  event:
    - pull_request

steps:
  - name: lint
    image: ghcr.io/tmknom/dockerfiles/prettier
    commands:
      - cd ./frontend
      - prettier --plugin-search-dir . --check
      # - eslint .

  - name: build
    depends_on:
      - lint
    image: plugins/docker
    settings:
      purge: false
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
      username: agrrh
      password:
        from_secret: docker_password
      repo: agrrh/quotes-frontend
      tags:
        - ${DRONE_COMMIT_BRANCH}
        - ${DRONE_COMMIT_SHA}

---

kind: pipeline
type: docker
name: master

trigger:
  event:
    - cron
    - push
    - tag

steps:
  - name: build-backend
    image: plugins/docker
    settings:
      purge: false
      context: ./backend
      dockerfile: ./backend/Dockerfile
      username: agrrh
      password:
        from_secret: docker_password
      repo: agrrh/quotes-backend
      auto_tag: true

  - name: build-frontend
    image: plugins/docker
    settings:
      purge: false
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
      username: agrrh
      password:
        from_secret: docker_password
      repo: agrrh/quotes-frontend
      auto_tag: true
