---

kind: pipeline
type: docker
name: lint

steps:
  - name: lint
    image: agrrh/cider:0.2.0
    commands:
      - go-task lint

---

kind: pipeline
type: docker
name: build

steps:
  - name: backend
    image: plugins/docker
    settings:
      context: ./backend
      username: agrrh
      password:
        from_secret: docker_password
      repo: agrrh/quotes-backend
      auto_tag: true

  - name: frontend
    image: plugins/docker
    settings:
      context: ./frontend
      username: agrrh
      password:
        from_secret: docker_password
      repo: agrrh/quotes-frontend
      auto_tag: true

---

kind: pipeline
type: docker
name: test

depends_on:
  - build

steps:
  - name: test
    image: agrrh/cider:0.2.0
    environment:
      APP_URL: "http://api:3000"
    commands:
      - sleep 15
      - go-task test

services:
  - name: postgres
    image: postgres:14.5
    environment:
      POSTGRES_USER: quotes
      POSTGRES_PASSWORD: password
      POSTGRES_DB: quotes

  - name: api
    image: agrrh/quotes-backend
    environment:
      POSTGRES_USER: quotes
      APP_DB_URL: "postgresql://quotes:password@postgres/quotes"
