---

kind: pipeline
type: docker
name: common

steps:
  - name: editorconfig
    image: mstruebing/editorconfig-checker:2.4.0
    commands:
      - ec -config .editorconfig -verbose

---

kind: pipeline
type: docker
name: docs

steps:
  - name: tests
    image: agrrh/cigp
    commands:
      - go-task docs:tests

---

kind: pipeline
type: docker
name: backend

steps:
  - name: tests
    image: agrrh/cigp
    commands:
      - go-task backend:tests

---

kind: pipeline
type: docker
name: frontend

steps:
  - name: tests
    image: agrrh/cigp
    commands:
      - go-task frontend:tests
