---

kind: pipeline
type: docker
name: lint

steps:
  - name: lint
    image: agrrh/cider:0.2.0
    commands:
      - go-task lint

---

kind: pipeline
type: docker
name: test

steps:
  - name: test
    image: agrrh/cider:0.2.0
    commands:
      - go-task test
