---

version: "3"

services:
  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      APP_ENV: local
    ports:
      - "8080:80"

  backend:
    build: ./backend
    depends_on:
      - postgres
    environment:
      APP_DB_URL: "postgresql://quotes:password@postgres/quotes"
    ports:
      - "8081:3000"

  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_USER: quotes
      POSTGRES_PASSWORD: password
      POSTGRES_DB: quotes
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
