---

version: "3"

services:
  frontend:
    build: ./frontend
    # depends_on:
    #   - backend
    environment:
      APP_ENV: local
    ports:
      - "8080:80"

  # backend:
  #   build: ./backend
  #   depends_on:
  #     - redis
  #   ports:
  #     - "8081:3000"
