---

apiVersion: skaffold/v3
kind: Config

metadata:
  name: quotes

build:
  artifacts:
    - image: agrrh/quotes-backend
      context: backend

    # - image: agrrh/quotes-frontend
    #   context: frontend

  tagPolicy:
    gitCommit:
        variant: Tags

manifests:
  rawYaml:
    - .kubernetes/dev/namespace.yaml
    - .kubernetes/dev/database/*
    - .kubernetes/dev/backend/*
    # - .kubernetes/dev/frontend/*

deploy:
  kubeContext: bugry1.spb.agrrh.com

portForward:
  # - resourceType: Service
  #   resourceName: frontend
  #   namespace: quotes-dev
  #   port: http
  #   localPort: 8080

  - resourceType: Service
    resourceName: backend
    namespace: quotes-dev
    port: http
    localPort: 8081
