---

version: '3'

tasks:
  docs:
    preconditions:
      - docsify --version
    cmds:
      - docsify serve ./docs

  dev:
    preconditions:
      - docker-compose --version
    cmds:
      - docker-compose up --build

  # test:
  #   preconditions:
  #     - python -c 'import sys; assert sys.version_info.major == 3'
  #   cmds:
  #     - sleep 0

  ci:
    # deps:
    #   - test
    cmds:
      - sleep 0
