---

version: '3'

includes:
  backend: ./backend
  frontend: ./frontend
  docs: ./docs

tasks:
  # Dev

  docs:
    preconditions:
      - docsify --version
    cmds:
      - docsify serve ./docs

  dev:
    preconditions:
      - skaffold version
    cmds:
      - skaffold dev

  # Linters

  common:lint:
    cmds:
      - ec -config .editorconfig -verbose

  lint:
    deps:
      - common:lint
      - docs:lint
      - backend:lint
      - frontend:lint

  # Tests

  test:
    deps:
      - docs:test
      - backend:test
      - frontend:test
