---

version: '3'

includes:
  docs:
    taskfile: ./docs/Taskfile.yml
    dir: ./docs

  backend:
    taskfile: ./backend/Taskfile.yml
    dir: ./backend

  frontend:
    taskfile: ./frontend/Taskfile.yml
    dir: ./frontend

tasks:
  docs:
    preconditions:
      - docsify --version
    cmds:
      - docsify serve ./docs

  dev:
    preconditions:
      - skaffold version
    cmds:
      - skaffold dev

  common:lint:
    preconditions:
      - ec -version
    cmds:
      - ec

  lint:
    deps:
      - common:lint
      - docs:lint
      - backend:lint
      - frontend:lint

  test:
    deps:
      - docs:test
      - backend:test
      - frontend:test
