---

version: '3'

tasks:
  docs:
    preconditions:
      - docsify --version
    cmds:
      - docsify serve ./docs

  dev:
    preconditions:
      - skaffold version
    cmds:
      - skaffold dev

  docs:tests:
    cmds:
      - sleep 0

  backend:tests:
    preconditions:
      - python -c 'import sys; assert sys.version_info.major == 3'
    cmds:
      - flake8 ./backend

  frontend:tests:
    cmds:
      - sleep 0
