---

version: '3'

tasks:
  lint:init:
    preconditions:
      - pip --version
    cmds:
      - pip install -r requirements.ci.txt

  lint:flake8:
    deps:
      - init
    preconditions:
      - flake8 --version
    cmds:
      - flake8 ./

  lint:black:
    deps:
      - init
    preconditions:
      - black --version
    cmds:
      - black --check --diff ./

  lint:
    deps:
      - lint:flake8
      - lint:black

  test:init:
    preconditions:
      - pip --version
    cmds:
      - pip install -r requirements.ci.txt

  test:
    preconditions:
      - python --version
    deps:
      - init
    cmds:
      - pytest ./tests
