---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: quotes-dev
  labels:
    app: quotes
    component: backend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: quotes
      component: backend

  template:
    metadata:
      labels:
        app: quotes
        component: backend

    spec:
      containers:
        - name: app
          image: agrrh/quotes-backend:latest

          # TODO: Move to secrets
          env:
            - name: APP_DB_DSN
              value: "quotes:CRK9aI5LvfS1ryYE@tcp(database:3306)/quotes?charset=utf8mb4&parseTime=True&loc=Local"

          ports:
            - name: http
              containerPort: 8081
