---

apiVersion: v1
kind: Service

metadata:
  name: database
  namespace: quotes-dev

spec:
  selector:
    app: quotes
    component: database
  ports:
    - name: postgres
      protocol: TCP
      port: 3306
      targetPort: 3306
