---

apiVersion: v1
kind: Service

metadata:
  name: frontend
  namespace: quotes-dev

spec:
  selector:
    app: quotes
    component: frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
