---

apiVersion: v1
kind: Service

metadata:
  name: postgres
  namespace: quotes-dev

spec:
  selector:
    app: quotes
    component: postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
